"""Typed state definitions for the DeepPilot research graph."""

from __future__ import annotations

import operator
from dataclasses import dataclass, field
from typing import TypedDict

from langgraph.graph import add_messages
from typing_extensions import Annotated


class OverallState(TypedDict):
    """State shared by the full research graph."""

    messages: Annotated[list, add_messages]
    search_query: Annotated[list, operator.add]
    web_research_result: Annotated[list, operator.add]
    sources_gathered: Annotated[list, operator.add]
    source_audit: Annotated[list, operator.add]
    citation_audit: dict
    final_answer: str
    visual_blocks: list
    initial_search_query_count: int
    max_research_loops: int
    research_loop_count: int
    reasoning_model: str
    research_plan: dict


class ReflectionState(TypedDict):
    """Structured output from the reflection node."""

    is_sufficient: bool
    knowledge_gap: str
    follow_up_queries: Annotated[list, operator.add]
    research_loop_count: int
    max_research_loops: int
    number_of_ran_queries: int


class Query(TypedDict):
    """Search query plus rationale generated by the query node."""

    query: str
    rationale: str


class QueryGenerationState(TypedDict):
    """State update containing generated search queries."""

    search_query: list[Query]


class WebSearchState(TypedDict):
    """Input state for one web-search branch."""

    search_query: str
    id: str


@dataclass(kw_only=True)
class SearchStateOutput:
    """Final graph output wrapper."""

    running_summary: str = field(default=None)  # Final report
